# Generated by Django 5.2.15 on 2026-06-09 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_name', models.CharField(max_length=100)),
                ('op_logo', models.ImageField(blank=True, default='default.png', null=True, upload_to='operator_logos/')),
                ('op_email', models.EmailField(max_length=254, unique=True)),
                ('op_mobile_no1', models.CharField(max_length=15)),
                ('op_mobile_no2', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('op_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
