# Generated by Django 5.2.15 on 2026-06-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_seats', '0002_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='seats.seat'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_seat_per_booking'),
        ),
    ]
