# Generated by Django 5.2.15 on 2026-06-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('sleeper', 'Sleeper'), ('ac_bus', 'AC Bus'), ('luxury', 'Luxury'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='operators.operator')),
            ],
        ),
    ]
